---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: letsencrypt-controller
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: letsencrypt-controller
    spec:
      containers:
        - image: tazjin/letsencrypt-controller:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: letsencrypt-controller
