apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: board
  namespace: default
  labels:
    app: board
spec:
  replicas: 2
  template:
    metadata:
    labels:
        app: board
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "board"
                    operator: In
                    values:
                    - board
              topologyKey: "kubernetes.io/hostname"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: board
  template:
    metadata:
      labels:
        app: board
    spec:
      containers:
      - name: board
        image: battlesnakeio/board:{{ .Values.release }}
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "2"
            memory: 1000M
          requests:
            cpu: "0.5"
            memory: 500M

