apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: engine-worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: engine-worker
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
