apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: engine-controller
  labels:
    app: engine-controller
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: engine-controller
  template:
    metadata:
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
      labels:
        app: engine-controller
    spec:
      containers:
      - name: engine
        image: battlesnakeio/engine:{{ .Values.release }}
        env:
        - name: POSTGRES_HOST
          value: "sqlproxy-engine-gcloud-sqlproxy.default.svc.cluster.local"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "engine"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: cloudsql-engine-db-credentials
              key: username
              optional: false
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cloudsql-engine-db-credentials
              key: password
              optional: false
        command: ["/bin/engine"]
        args:
          [
            "server",
            "controller",
            "-l",
            ":3002",
            "-b",
            "sql",
            "-a",
            "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=disable",
          ]
        resources:
          limits:
            cpu: "1"
            memory: 750M
          requests:
            cpu: "0.5"
            memory: 500M
        ports:
          - containerPort: 3002
          - containerPort: 3004
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: engine-api
  labels:
    app: engine-api
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: engine-api
  template:
    metadata:
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
      labels:
        app: engine-api
    spec:
      containers:
      - name: engine
        image: battlesnakeio/engine:{{ .Values.release }}
        command: ["/bin/engine"]
        args:
          [
            "server",
            "api",
            "-c",
            "engine-controller:3004",
          ]
      resources:
        limits:
          cpu: "1"
          memory: 750M
        requests:
          cpu: "0.5"
          memory: 500M
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: engine-socket
  labels:
    app: engine-socket
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: engine-socket
  template:
    metadata:
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
      labels:
        app: engine-socket
    spec:
      containers:
      - name: engine
        image: battlesnakeio/engine:{{ .Values.release }}
        command: ["/bin/engine"]
        args:
          [
            "server",
            "api",
            "-c",
            "engine-controller:3004",
          ]
      resources:
        limits:
          cpu: "1"
          memory: 750M
        requests:
          cpu: "0.5"
          memory: 500M
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: engine-worker
  labels:
    app: engine-worker
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: engine-worker
  template:
    metadata:
      annotations:
        prometheus.io/port: "9000"
        prometheus.io/scrape: "true"
      labels:
        app: engine-worker
    spec:
      containers:
      - name: engine
        image: battlesnakeio/engine:{{ .Values.release }}
        command: ["/bin/engine"]
        args:
          [
            "server",
            "worker",
            "-c",
            "engine-controller:3004",
            "-t",
            "50",
          ]
      resources:
        limits:
          cpu: "1"
          memory: 750M
        requests:
          cpu: "0.5"
          memory: 500M
