apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: engine
  namespace: default
  labels:
    app: engine
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
        - name: engine
          image: battlesnakeio/engine:0.2.4
          env:
          - name: POSTGRES_HOST
            value: "sqlproxy-engine-gcloud-sqlproxy"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: "engine"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: cloudsql-engine-db-credentials
                key: username
                optional: false
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-engine-db-credentials
                key: password
                optional: false
          command: ["/bin/engine"]
          args:
            [
              "server",
              "-l",
              ":3002",
              "-t",
              "1",
              "-b",
              "sql",
              "-a",
              "postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):$(POSTGRES_PORT)/$(POSTGRES_DB)?sslmode=disable",
            ]
          ports:
            - containerPort: 3002
            - containerPort: 3004
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: engine-worker
  namespace: default
  labels:
    app: engine
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: engine
  template:
    metadata:
      labels:
        app: engine
    spec:
      containers:
        - name: engine
          image: battlesnakeio/engine:0.2.4
          command: ["/bin/engine"]
          args:
            [
              "server",
              "worker",
              "-c",
              "engine:3004",
              "-t",
              "50",
            ]
