apiVersion: v1
kind: Service
metadata:
  name: engine
  namespace: default
spec:
  selector:
    app: engine
  ports:
    - name: http
      protocol: 'TCP'
      port: 80
      targetPort: 3002
    - name: controller
      protocol: 'TCP'
      port: 3004
      targetPort: 3004
