apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: default
  annotations:
    external-dns.alpha.kubernetes.io/hostname: nginx.{{ .Values.domain }}.
    acme/certificate: nginx.{{ .Values.domain }}
spec:
  type: LoadBalancer
  ports:
  - name: nginx
    port: 443
    targetPort: 443
  selector:
    app: nginx
