apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-test
  namespace: default
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: "{{ .Values.certificateName }}"
    ingress.kubernetes.io/ssl-redirect: "true"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - host: test.{{ .Values.domain }}
      http:
        paths:
        - path: /
          backend:
            serviceName: nginx-test
            servicePort: 80