apiVersion: v1
kind: Service
metadata:
  name: nginx-test
  namespace: default
  labels:
    version: "{{ .Chart.Version }}"
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: nginx-test
