apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.opensource.zalan.do/teapot/external-dns:{{ .Values.image.tag }}
        args:
        - --source=service
        - --source=ingress
        - --domain-filter={{ .Values.domain }} # will make ExternalDNS see only the hosted zones matching provided domain, omit to process all available hosted zones
        - --provider=google
        - --google-project={{ .Values.googleProjectId }} # Use this to specify a project different from the one external-dns is running inside
        - --registry=txt
        - --txt-owner-id=my-identifier