apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: play
  namespace: default
  labels:
    app: play
spec:
  replicas: 2
  template:
    metadata:
    labels:
        app: play
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                    - play
              topologyKey: "kubernetes.io/hostname"
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 2
  selector:
    matchLabels:
      app: play
  template:
    metadata:
      labels:
        app: play
    spec:
      containers:
      - name: play
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        env:
          - name: ENGINE_URL
            value: "https://engine.battlesnake.io"
          - name: BOARD_URL
            value: "https://board.battlesnake.io"
          - name: ENV
            value: "production"
          - name: BATTLESNAKEIO_DOMAIN
            value: ".battlesnake.io"
          - name: POSTGRES_HOST
            value: "sqlproxy-gcloud-sqlproxy"
          - name: POSTGRES_PORT
            value: "5432"
          - name: POSTGRES_DB
            value: "play"
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef: 
                name: cloudsql-play-db-credentials
                key: username
                optional: false
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: cloudsql-play-db-credentials
                key: password
                optional: false
          - name: SENTRY_KEY
            valueFrom:
              secretKeyRef:
                name: sentry-key
                key: key
                optional: false
          - name: BATTLESNAKEIO_GITHUB_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: github-oauth
                key: id
                optional: false
          - name: BATTLESNAKEIO_GITHUB_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: github-oauth
                key: secret
                optional: false
          - name: BATTLESNAKEIO_SECRET
            valueFrom:
              secretKeyRef:
                name: battlesnake-secret
                key: secret
                optional: false
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "0.5"
            memory: 500M
          requests:
            cpu: "0.5"
            memory: 500M
