apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: default
data:
  index.html: |
    <html>
      <head><title>Battlesnake Maintenance</title></head>
        <body>
          <div style="text-align: center">
            <h1>Battlesnake is currently down for maintenance.</h1>
          </div>
        </body>
    </html>
  nginx.conf: |
    events {}
    http {
      server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/;
        index index.html;
        location / {
          try_files $uri $uri/ =404;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: maintenance
  namespace: default
spec:
  selector:
    app: maintenance
  ports:
    - name: http
      protocol: 'TCP'
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: maintenance
  namespace: default
  labels:
    app: maintenance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maintenance
  template:
    metadata:
      labels:
        app: maintenance

    spec:
      containers:
      - name: maintenance
        image: nginx
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: nginx-config
          mountPath: /var/www/index.html
          subPath: index.html
        ports:
        - containerPort: 80
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config