apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: kube-system
spec:
  acme:
    server: https://acme-v01.api.letsencrypt.org/directory
    email: admin@battlesnake.io
    privateKeySecretRef:
      name: letsencrypt-prod
    http01: {}
